development:
  adapter: mysql2
  encoding: utf8
  database: contact-plus_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: contact-plus_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: contact-plus_production
  pool: 5
  username: root
  password:
  host: localhost
